name: C++ CI Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kodu
      uses: actions/checkout@v4

    - name: Kompilacia aplikacie
      run: g++ calculator.cpp -o kalkulacka

    - name: Spustenie testu (Delenie nulou)
      run: |
        echo "10 0" | ./kalkulacka
